name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore workloads dependencies
      run: dotnet workload restore Galeon.sln
    - name: Restore dependencies
      run: dotnet restore Galeon.sln
    - name: Build
      run: dotnet build Galeon.sln --no-restore
    - name: Test
      run: dotnet test Galeon.sln --no-build --verbosity normal