name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Restore GaleonServer dependencies
      run: dotnet restore src/GaleonServer/GaleonServer.Api/GaleonServer.Api.csproj
    - name: Build GaleonServer
      run: dotnet build src/GaleonServer/GaleonServer.Api/GaleonServer.Api.csproj --no-restore
    - name: Unit tests
      run: dotnet test src/unit_tests/GaleonServer.UnitTests/GaleonServer.UnitTests.csproj
    - name: Integration tests
      run: dotnet test src/integration_tests/GaleonServer.ContractTests/GaleonServer.ContractTests.csproj
    - name: Run SpecFlow Tests
      uses: cryptic-wizard/run-specflow-tests@v1.3.1