name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Unit tests
      run: dotnet test src/unit_tests/GaleonServer.UnitTests/GaleonServer.UnitTests.csproj
    - name: Integration tests
      run: dotnet test src/integration_tests/GaleonServer.ContractTests/GaleonServer.ContractTests.csproj
    - name: Build GaleonServer
      run: dotnet build src/GaleonServer/GaleonServer.Api/GaleonServer.Api.csproj
    - name: Run SpecFlow Tests
      run: dotnet test src/integration_tests/GaleonServer.BehaviourContractTests/GaleonServer.BehaviourContractTests.csproj
    - name: Create SpecFlow Tests documentation
      uses: cryptic-wizard/run-specflow-tests@v1.3.1
      with:
        test-assembly-path: src/integration_tests/GaleonServer.BehaviourContractTests/bin/Debug/net6.0
        test-assembly-dll: GaleonServer.BehaviourContractTests.dll
        output-html: GaleonServerBehaviourContractTestsResults.html
        no-build: true